version: '3.8'

services:
    db:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        ports:
            - "3310:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: db
            MYSQL_USER: arris
            MYSQL_PASSWORD: password
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - mynetwork

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        restart: unless-stopped
        ports:
            - "8082:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge

volumes:
    dbdata:
